### ISSUE TITLE
Please encrypt passwords

### ISSUE THREAD

**Issue by mcm1957** [Standarduser/ioBroker.meater#4]
Please encrypt passwords during storage.

Only 2 entries intp io-package.json are required to enhance the security.

See: https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

```
if you need to store passwords please encrypt them. This can be done by just configuration:
Add an array with the relevant config-fieldnames in io-package.json in "encryptedNative". Additionally please also protect the access to this field by also providing "protectedNative" (see e.g. https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L81-L82)
Additionally you need to provide a dependency to js-controller >= 3.0.0 and admin 4.0.9. (Admin needs to be a "globalDependency", see https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L75-L80 and https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L70-L74)
That's it. Encryption before storing the fields and decryption before adapter is executed is done automatically.
```

Thanks for spending your time and working at this adapter. And sorry to bother you with an issue at this early state. But now changing to encrypted store would only affect you but later all (test-)user would be required to renter the password when changing to encrypted storage.

**Comment by mcm1957** [comment]
Just for info:
Encrypting passwords will be request during review of adapter before adding it to official repositories.
(At least thats my current knowledge)

**Comment by Standarduser** [comment]
done
